project_id = "wpwdxtyufpewdyffxlgo"

[functions.send-notification]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-setup-webhook]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
