-- Add customer_email column to orders table
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_email text;

-- Create storage bucket for payment proofs (private)
INSERT INTO storage.buckets (id, name, public)
VALUES ('proof-uploads', 'proof-uploads', false)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for proof-uploads bucket
-- Users can upload their own proofs
CREATE POLICY "Users can upload payment proofs"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'proof-uploads' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Users can view their own proofs
CREATE POLICY "Users can view own payment proofs"
ON storage.objects
FOR SELECT
TO authenticated
USING (
  bucket_id = 'proof-uploads' 
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Admins can view all proofs
CREATE POLICY "Admins can view all payment proofs"
ON storage.objects
FOR SELECT
TO authenticated
USING (
  bucket_id = 'proof-uploads' 
  AND has_role(auth.uid(), 'admin'::app_role)
);

-- Staff can view proofs for completed payment orders (using service role for signed URLs in edge function)
-- Note: Staff access is controlled at application level via signed URLs generated by admins

-- Add new notification types to trigger function for customer emails
CREATE OR REPLACE FUNCTION public.trigger_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  payload JSONB;
  notification_type TEXT;
  edge_function_url TEXT;
  log_id UUID;
  request_id BIGINT;
  customer_email TEXT;
BEGIN
  -- Get customer email from the order/ticket_request
  IF TG_TABLE_NAME = 'orders' THEN
    customer_email := NEW.customer_email;
  ELSIF TG_TABLE_NAME = 'ticket_requests' THEN
    customer_email := NEW.contact_email;
  END IF;

  -- Determine notification type based on trigger
  IF TG_TABLE_NAME = 'ticket_requests' AND TG_OP = 'INSERT' THEN
    notification_type := 'new_ticket_request';
    payload := jsonb_build_object(
      'type', notification_type,
      'data', jsonb_build_object(
        'origin', NEW.origin,
        'destination', NEW.destination,
        'departureDate', NEW.departure_date::TEXT,
        'returnDate', NEW.return_date::TEXT,
        'passengers', NEW.passengers,
        'cabinClass', NEW.cabin_class,
        'budget', NEW.budget,
        'contactEmail', NEW.contact_email
      )
    );
  ELSIF TG_TABLE_NAME = 'orders' AND TG_OP = 'INSERT' THEN
    notification_type := 'new_order';
    payload := jsonb_build_object(
      'type', notification_type,
      'data', jsonb_build_object(
        'orderId', NEW.id::TEXT,
        'amount', NEW.amount_paid,
        'paymentMethod', NEW.payment_method,
        'voucherId', NEW.voucher_id::TEXT,
        'customerEmail', NEW.customer_email
      ),
      'customerEmail', NEW.customer_email
    );
  ELSIF TG_TABLE_NAME = 'orders' AND TG_OP = 'UPDATE' THEN
    -- Payment proof uploaded
    IF NEW.proof_upload_url IS NOT NULL AND (OLD.proof_upload_url IS NULL OR OLD.proof_upload_url <> NEW.proof_upload_url) THEN
      notification_type := 'payment_proof_uploaded';
      payload := jsonb_build_object(
        'type', notification_type,
        'data', jsonb_build_object(
          'orderId', NEW.id::TEXT,
          'amount', NEW.amount_paid,
          'paymentMethod', NEW.payment_method,
          'proofUrl', NEW.proof_upload_url
        ),
        'customerEmail', NEW.customer_email
      );
    -- Payment approved (status changed to completed)
    ELSIF NEW.payment_status = 'completed' AND OLD.payment_status <> 'completed' THEN
      notification_type := 'payment_approved';
      payload := jsonb_build_object(
        'type', notification_type,
        'data', jsonb_build_object(
          'orderId', NEW.id::TEXT,
          'amount', NEW.amount_paid,
          'voucherId', NEW.voucher_id::TEXT
        ),
        'customerEmail', NEW.customer_email
      );
    -- Payment rejected (status changed to failed)
    ELSIF NEW.payment_status = 'failed' AND OLD.payment_status <> 'failed' THEN
      notification_type := 'payment_rejected';
      payload := jsonb_build_object(
        'type', notification_type,
        'data', jsonb_build_object(
          'orderId', NEW.id::TEXT,
          'amount', NEW.amount_paid,
          'rejectionReason', NEW.admin_notes
        ),
        'customerEmail', NEW.customer_email
      );
    -- Order delivered
    ELSIF NEW.order_status = 'delivered' AND OLD.order_status <> 'delivered' THEN
      notification_type := 'order_delivered';
      payload := jsonb_build_object(
        'type', notification_type,
        'data', jsonb_build_object(
          'orderId', NEW.id::TEXT,
          'deliveryInfo', NEW.delivery_info
        ),
        'customerEmail', NEW.customer_email
      );
    ELSE
      RETURN NEW;
    END IF;
  ELSE
    RETURN NEW;
  END IF;

  -- Log the attempt with recipient
  INSERT INTO public.notification_log (event_type, record_id, status, payload, recipient)
  VALUES (notification_type, NEW.id, 'pending', payload, COALESCE(customer_email, 'admin'))
  RETURNING id INTO log_id;

  -- Build edge function URL
  edge_function_url := 'https://wpwdxtyufpewdyffxlgo.supabase.co/functions/v1/send-notification';

  -- Call edge function via pg_net
  SELECT net.http_post(
    url := edge_function_url,
    body := payload,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwd2R4dHl1ZnBld2R5ZmZ4bGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MzI3NTQsImV4cCI6MjA4MjQwODc1NH0.seaxklRqvLLdqloVqEeKDg8P1fZlWLP5hrMuaOMfChE'
    )
  ) INTO request_id;

  -- Update log status
  UPDATE public.notification_log SET status = 'sent' WHERE id = log_id;

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  IF log_id IS NOT NULL THEN
    UPDATE public.notification_log SET status = 'error', error = SQLERRM WHERE id = log_id;
  ELSE
    INSERT INTO public.notification_log (event_type, record_id, status, error, payload, recipient)
    VALUES (COALESCE(notification_type, 'unknown'), NEW.id, 'error', SQLERRM, payload, COALESCE(customer_email, 'admin'));
  END IF;
  RETURN NEW;
END;
$$;

-- Ensure triggers exist for orders UPDATE
DROP TRIGGER IF EXISTS notify_order_update ON public.orders;
CREATE TRIGGER notify_order_update
  AFTER UPDATE ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.trigger_notification();